---
title: "Exploratory Analysis"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuious.color = "viridis",
  ggplot2.continuious.fill = "viridis"
  
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

```

## "group_by"

```{r}
weather_df %>% 
  group_by(name, month)  
view(weather_df)
```

## Counting things 

count month observations:
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())

```

we can use count()

```{r}
weather_df %>% 
  count(name, month, name = "n_obs")
```

NEVER use base R and use table()

## 2x2 tables 

```{r}
weather_df %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE  ~ ""
    )
  ) %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
 
```

use tabyl(,) to create 2x2 tables 
```{r}
weather_df %>% 
  filter(name != "Molokai_HI") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE  ~ ""
    )
  ) %>% 
  janitor::tabyl(name, cold)
```


## General summaries 

You can do lots of summaries 

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    mean_tmin = mean(tmin, na.rm = TRUE),
  )
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    mean_tmin = mean(tmin, na.rm = TRUE)
  ) %>% 
ggplot(aes(x = month, y = mean_tmax)) +
  geom_point() + 
  geom_line()
```

Suppose you want to summarize many columns -- Use summarize(across(:))

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))
```

Sometimes results are easier to read in another format

```{r}
weather_df %>% 
    group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 1)

```

## 'group_by()' and 'mutate()'

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

What about window functions? 

ranking...
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(temp_rank = min_rank(tmax)) %>% 
  filter(temp_rank == 1)
```

lag

```{r}
weather_df %>% 
    group_by(name) %>% 
  mutate(temp_change = tmax - lag(tmax)) %>% 
  summarize(
    temp_change_max = max(temp_change, na.rm = TRUE),
    temp_change_sd = sd(temp_change, na.rm = TRUE)
  )
```

